### ISSUE TITLE
SPI setup

### ISSUE THREAD

**Issue by PeterQFR** [piranha32/IOoo#1]
Hi 
I'm trying to do the same thing with a BeagleBone C++ library. And want to implement your SPI library as it seems more advanced. However, in the SPI::open, shouldn't the pins for the SPI be setup as outputs or inputs? or is this not required for SPI in linux?

cheers
Peter

**Comment by piranha32** [comment]
Opening the SPI device file has nothing to do with pin directions. In modern kernels directions of pins are configured by device tree. The main file is loaded on boot, but on Beaglebone you can load later overlays, which amend the original device tree and can be used to set pin configurations during run time. Another function of the overlays is to load and configure device drivers. The overlay that you will load will tell the kernel that the SPI driver should be attached to the pins and since this moment they can only be controlled by SPI subsystem.
Angstrom comes with a bunch of overlay files for most of the on-chip devices. You can find the them in /lib/firmware/. You can also write your own overlay using the sources of overlays from Angstrom or dts/spi1-00A0.dts from the library.
To load an overlay you have to write its name to /sys/devices/bone_capemgr._/slots: e.g. the following command will enable SPI0 on Angstrom:
```echo SPIDEV0 > /sys/devices/bone_capemgr._/slots```
This is the great place to start if you know nothing about overlays: https://github.com/jadonk/validation-scripts/tree/master/test-capemgr If you want to read more, hipstercircuits has a very good description of the first steps: http://hipstercircuits.com/adding-beaglebone-cape-support-to-a-kernel-with-device-tree-in-ubuntu/

**Comment by PeterQFR** [comment]
Thanks. I also reviewed one of derek molloy's videos on the subject: http://www.youtube.com/watch?v=wui_wU1AeQc
 But from what I can see, the device tree seems to only streamline setup of the GPIO pins MUX settings for a fixed arrangement, such as a cape.
From looking through your code, I noticed that you dont use the file interfaces in the /sys/class/ folder, but seem to use the memory mapped versions in the /dev/ folder. Does this functionality come directly from setting up the device tree overlay? 
Also I implemented the SPI interface reading two bytes from a sensor a couple of nights ago in a while loop to evaluate what speed I was getting. In the SetSpeed() I wrote 500000, but the oscilloscope was only showing a 320KHz transmission rate. The sensor is capable of speeds up to 1MHz. Additionally between reads was a 50 us delay, is there some way to reduce this? Or do you think that is a pause in the ubuntu OS.

**Comment by piranha32** [comment]
mmap is used to access GPIOs. SPI is accessed through /dev/ interface.
